version: "3.9"

services:
  app:
    build: .
    container_name: tbs_app
    ports:
      - "8271:8271"
    #environment:
    #  - TBS_DB_DSN="dbo:Znmml2mkNuXaHDp@tcp(db:3306)/tinybuildserver?charset=utf8&parseTime=true"
    volumes:
      - appdata:/app/data
    depends_on:
      - db
    networks:
      - tbs_net

  db:
    image: "mysql:5.7"
    container_name: tbs_db
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Y0oc2uITDWoJjnI
      - MYSQL_DATABASE=tinybuildserver
      - MYSQL_USER=dbo
      - MYSQL_PASSWORD=Znmml2mkNuXaHDp
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - tbs_net


networks:
  tbs_net:
    driver: bridge

volumes:
  appdata: