version: "3.9"

services:
  dbservice:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=tinybuildserver
      - MYSQL_USER=dbo
      - MYSQL_PASSWORD=Znmml2mkNuXaHDp
    ports:
      - "3306:3306"
    networks:
      - local

  app:
    build: .
    ports:
      - "8271:8271"
    environment:
      - TBS_DB_DSN=${TBS_DB_DSN}
    depends_on:
      - dbservice
    networks:
      - local


networks:
  local: